### ISSUE TITLE
Integration HA

### ISSUE THREAD

**Issue by BornTKill** [ssenart/PyVeoliaIDF#1]
Bonjour,

Le projet vise une intégration dans HA. Je me disais peut être que comme pour gazpar tu aurais une branche HA sur laquelle je pourrais tester VeoliaIDF ?

Merci pour ton travail.

PS: je vais tester ton component gazpar très vite.

**Comment by ssenart** [comment]
Bonjour,

Oui, en effet, elle est ici : https://github.com/ssenart/home-assistant/tree/veoliaidf

Stéphane

**Comment by BornTKill** [comment]
Merci !

**Comment by BornTKill** [comment]
Désolé mais je veux valider la procédure sur Raspbian Lite. histoire d’éviter de pourrir mon Pi pour rien :) Tu tournes sur Pi ?

**Comment by ssenart** [comment]
Non, je suis avec l'image officiel docker de HA. Sous raspbian, cela devrait fonctionner sans problème.

**Comment by BornTKill** [comment]
Ok. Tu peux me dire les commandes de ton dockerfile ? Merci.

**Comment by ssenart** [comment]
Pas de dockerfile personnalisé, j'utilise directement l'image avec compose et le volume monté pour les config et les custom_components :

version: '2'

services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    restart: always
    network_mode: host
    volumes:
      - ${HA_CONFIG_PATH}:/config

**Comment by BornTKill** [comment]
Ok mais pour ton component tu ajoutes firefox et geodriver dans l’image ?

**Comment by ssenart** [comment]
Oui, en effet:
- Firefox : je me loge dans le container et rajoute manuellement. Et c'est vrai qu'un dockerfile te permettra de le faire automatiquement (commande de mémoire : apk add firefox-esr).
- WebDriver : Il est sur mon hôte dans le dossier config (montage volume).

**Comment by BornTKill** [comment]
Bonjour,

Je te remercier pour ton aide et ce projet. J’ai ajouté avec succès (a première vue, on verra si c’est stable) gazpar et veoliaIDF. Je songe à porter un script python vers API domoticz dans Ha. Est ce que l’approche script + API HA est la bonne (et est à ma portée) ou dois je partir sur un component plutôt. Fonctionnellement le script fait des commandes telnet, relève des valeurs (consignes/capteurs chaudière) et update des métriques dans HA. Également des switchs côté HA doivent permettre passer des commandes telnet à la chaudière en consigne.

Bonne journée.

**Comment by ssenart** [comment]
Quelle est la marque de ta chaudière ? L'approche "Component" à l'avantage d'être standard pour HA et en plus tu pourras la proposer au projet pour intégration. Elle sera plus facilement partageable.

**Comment by BornTKill** [comment]
Bonsoir.

Viessman Vitodens 200 avec un module de communication https://github.com/openv/openv/wiki/Bauanleitung-3.3V-TTL.
Le pilotage ce fait via vitalk https://github.com/openv/vitalk/blob/master/doc/ViTalk.md
